---
title: "Brazilian Parties Data 2023"
author: "Natan Duarte"
format: html
editor: visual
---

## Gastos da Câmara em 2023

```{r}
R.version.string
```

## Obtenção dos dados

Primeiro foi realizado o dowload e unzip da base de dados

```{r}
#| echo: false

url <- 'https://www.camara.leg.br/cotas/Ano-2023.csv.zip'

zip_name <- 'Gastos-Camara-Ano-2023.zip'

folder_name <- 'Gastos-Camara'
file_name <- 'Ano-2023.csv'
file_path <- file.path(folder_name, file_name)


tryCatch(
  expr = {
    # Se não houver exceções, o código dentro deste bloco será executado
    download.file(url, zip_name, mode = "wb")
    cat("Download concluído com sucesso!\n")
  },
  error = function(e) {
    # Se ocorrer uma exceção, o código dentro deste bloco será executado
    cat("Erro durante o download: ", conditionMessage(e), "\n")
  }
)
```

Depois do unzip, podemos deletar o arquivo compactado

```{r}

tryCatch(
  expr = {
    # validate if the file exists before performing action
    
    unzip(zip_name, exdir = folder_name)
    file.remove(zip_name)
    cat("Unzip concluído com sucesso e arquivo deletado!\n")
  },
  error = function(e) {
    cat("Erro durante o unzip: ", conditionMessage(e), "\n")
  }
)

```

Agora podemos capturar os dados do arquivo .csv

```{r}
library(dplyr)
library(psych)


parties_df <- read.csv2(file_path, sep=";")

sample_n(parties_df, 5)
```

## Limpeza de dados

### 1 - Validando a integridade

Vamos usar alguns métodos para avaliar a integridade.

```{r}



```
